# Generated by Django 5.0.8 on 2024-10-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "cod_conductor",
                    models.CharField(
                        max_length=9,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "apellido_paterno",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Apellido Paterno",
                    ),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Apellido Materno",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("01", "Pendiente"),
                            ("02", "Ausente"),
                            ("03", "Ocupado"),
                            ("04", "Disponible"),
                        ],
                        default="01",
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "alquileres_realizados",
                    models.IntegerField(default=0, verbose_name="Alquiler realizados"),
                ),
                (
                    "alquileres_cancelados",
                    models.IntegerField(default=0, verbose_name="Alquiler cancelado"),
                ),
            ],
            options={
                "verbose_name": "Conductor",
                "verbose_name_plural": "Conductores",
                "index_together": {("estado", "nombre", "apellido_paterno")},
            },
        ),
    ]
