# Generated by Django 5.0.8 on 2024-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_conductor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conductor",
            name="estado",
            field=models.CharField(
                choices=[
                    ("01", "Pendiente"),
                    ("02", "Ausente"),
                    ("03", "Ocupado"),
                    ("04", "Disponible"),
                    ("05", "Baja"),
                ],
                default="01",
                max_length=2,
                verbose_name="Estado",
            ),
        ),
    ]
