# Generated by Django 5.0.8 on 2025-02-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_conductor", "0002_alter_conductor_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="conductor",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Direccion"
            ),
        ),
        migrations.AddField(
            model_name="conductor",
            name="telefono",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefono"
            ),
        ),
    ]
