# Generated by Django 5.0.8 on 2025-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_conductor", "0003_conductor_direccion_conductor_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="conductor",
            name="clase",
            field=models.CharField(
                blank=True, max_length=1, null=True, verbose_name="Clase"
            ),
        ),
        migrations.AddField(
            model_name="conductor",
            name="estado_eeuu",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Estado EEUU"
            ),
        ),
        migrations.AddField(
            model_name="conductor",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True, verbose_name="Vencimiento"),
        ),
        migrations.AddField(
            model_name="conductor",
            name="licencia",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Licencia"
            ),
        ),
    ]
