# Generated by Django 5.0.8 on 2024-10-09 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_maestras", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatHorarioOperardor",
            fields=[
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        max_length=9,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha fin"),
                ),
                ("activo", models.BooleanField(default=False, verbose_name="Activo")),
                (
                    "cat_horario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_maestras.grupohorario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalogo de horario del operador",
                "verbose_name_plural": "Catalogo de horarios del operador",
            },
        ),
        migrations.CreateModel(
            name="Operador",
            fields=[
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        max_length=9,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código",
                    ),
                ),
                ("nombre", models.CharField(max_length=60, verbose_name="Nombre")),
                (
                    "apellido_paterno",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Apellido Paterno",
                    ),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Apellido Materno",
                    ),
                ),
                (
                    "alias",
                    models.CharField(blank=True, max_length=50, verbose_name="Alias"),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Extensión"
                    ),
                ),
                ("estado", models.BooleanField(default=False, verbose_name="Estado")),
                (
                    "rogramacion_automatica",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Programación automática"
                    ),
                ),
                (
                    "sesion_turno_activa",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sesión id turno activo"
                    ),
                ),
                (
                    "grupo_horario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_maestras.grupohorario",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Operador",
                "verbose_name_plural": "Operadores",
            },
        ),
        migrations.CreateModel(
            name="CatHorarioOperardorDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha fin"),
                ),
                ("activo", models.BooleanField(default=False, verbose_name="Activo")),
                (
                    "confirmado",
                    models.BooleanField(default=False, verbose_name="Confirmado"),
                ),
                (
                    "cat_horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_operador.cathorariooperardor",
                    ),
                ),
                (
                    "grupo_horario_detalle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_maestras.grupohorariodetalle",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_operador.operador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de catalogo de horario",
                "verbose_name_plural": "Detalles de catalogo de horario",
                "unique_together": {("cat_horario", "grupo_horario_detalle")},
            },
        ),
    ]
