# Generated by Django 5.0.8 on 2024-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_operador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cathorariooperardordetalle",
            name="fecha_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora fin"
            ),
        ),
        migrations.AlterField(
            model_name="cathorariooperardordetalle",
            name="fecha_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora inicio"
            ),
        ),
    ]
