# Generated by Django 5.0.8 on 2025-04-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_maestras", "0001_initial"),
        ("core_operador", "0002_alter_cathorariooperardordetalle_fecha_fin_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cathorariooperardordetalle",
            unique_together={("cat_horario", "grupo_horario_detalle", "operador")},
        ),
    ]
