# Generated by Django 5.0.8 on 2024-10-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_conductor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "cod_vehiculo",
                    models.SlugField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nom_vehiculo",
                    models.CharField(max_length=10, unique=True, verbose_name="Nombre"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                ("marca", models.CharField(max_length=50, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=50, verbose_name="Modelo")),
                (
                    "estado_vehiculo",
                    models.CharField(
                        choices=[
                            ("01", "Pendiente"),
                            ("02", "Fuera servicio"),
                            ("03", "Activo"),
                        ],
                        default="01",
                        max_length=2,
                        verbose_name="Estado vehículo",
                    ),
                ),
                (
                    "estado_alquilado",
                    models.CharField(
                        choices=[
                            ("01", "No Aplica"),
                            ("02", "Alquilado"),
                            ("03", "Liberado"),
                        ],
                        default="01",
                        max_length=2,
                        verbose_name="Estado alquiler",
                    ),
                ),
                (
                    "observacion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Observaciones",
                    ),
                ),
                (
                    "para_alquiler",
                    models.BooleanField(default=False, verbose_name="Para Alquilar"),
                ),
            ],
            options={
                "verbose_name": "Vehiculo",
                "verbose_name_plural": "Vehiculos",
                "index_together": {
                    ("estado_vehiculo", "estado_alquilado", "para_alquiler")
                },
            },
        ),
        migrations.CreateModel(
            name="AlquilerVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "monto_alquiler",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Monto alquiler",
                    ),
                ),
                (
                    "fecha_prog_inicio",
                    models.DateField(
                        blank=True, verbose_name="Fecha programación - Inicio"
                    ),
                ),
                (
                    "hora_prog_inicio",
                    models.TimeField(
                        blank=True, verbose_name="Hora programación - Inicio"
                    ),
                ),
                (
                    "fecha_prog_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha programación - Fin"
                    ),
                ),
                (
                    "hora_prog_fin",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora programación - Fin"
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha Inicio"
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(blank=True, null=True, verbose_name="Hora inicio"),
                ),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="Fecha Fin"),
                ),
                (
                    "hora_fin",
                    models.TimeField(blank=True, null=True, verbose_name="Hora Fin"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("01", "Pendiente"),
                            ("02", "Programado"),
                            ("03", "En proceso"),
                            ("04", "Concluido"),
                            ("05", "Cancelado"),
                            ("06", "Reprogramado"),
                        ],
                        default="01",
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "entrega_radio",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Entrega radio"
                    ),
                ),
                (
                    "programacion_automatica",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="Programación automática"
                    ),
                ),
                (
                    "observacion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Obs. servicio",
                    ),
                ),
                (
                    "conductor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_conductor.conductor",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_vehiculo.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alquiler de Vehiculo",
                "verbose_name_plural": "Alquiler de Vehiculos",
                "index_together": {("estado", "fecha_inicio", "fecha_fin")},
            },
        ),
    ]
