# Generated by Django 5.0.8 on 2024-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_vehiculo", "0001_initial"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="alquilervehiculo",
            index_together=set(),
        ),
        migrations.AddField(
            model_name="alquilervehiculo",
            name="fecha_hora_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora fin"
            ),
        ),
        migrations.AddField(
            model_name="alquilervehiculo",
            name="fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora inicio"
            ),
        ),
        migrations.AddField(
            model_name="alquilervehiculo",
            name="prog_fecha_hora_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Programación fecha hora fin"
            ),
        ),
        migrations.AddField(
            model_name="alquilervehiculo",
            name="prog_fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Programación fecha hora inicio"
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="estado_vehiculo",
            field=models.CharField(
                choices=[
                    ("01", "Pendiente"),
                    ("02", "Fuera servicio"),
                    ("03", "Activo"),
                    ("04", "Baja"),
                ],
                default="01",
                max_length=2,
                verbose_name="Estado vehículo",
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="nom_vehiculo",
            field=models.SmallIntegerField(unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterIndexTogether(
            name="alquilervehiculo",
            index_together={
                (
                    "estado",
                    "prog_fecha_hora_inicio",
                    "prog_fecha_hora_fin",
                    "fecha_hora_inicio",
                    "fecha_hora_fin",
                )
            },
        ),
    ]
