# Generated by Django 5.0.8 on 2024-11-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_vehiculo", "0002_alter_alquilervehiculo_index_together_and_more"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="vehiculo",
            index_together={
                ("estado_vehiculo", "estado_alquilado", "para_alquiler", "nom_vehiculo")
            },
        ),
    ]
