# Generated by Django 5.0.8 on 2025-03-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_vehiculo", "0003_alter_vehiculo_index_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="matricula",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Matrícula"
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Descripción"
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="marca",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Marca"
            ),
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="modelo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Modelo"
            ),
        ),
    ]
