# Generated by Django 5.0.8 on 2025-07-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_vehiculo",
            "0004_vehiculo_matricula_alter_vehiculo_descripcion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="numero_vin",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="VIN"
            ),
        ),
    ]
