# estado de llamada
ESTADO_LLAMADA_ENTRANTE = "01"
ESTADO_LLAMADA_LLAMANDO = "02"
ESTADO_LLAMADA_PERDIDA = "03"
ESTADO_LLAMADA_CONTESTADA = "04"
ESTADO_LLAMADA_ATENDIDO = "05"

ESTADO_LLAMADA_CHOICES = (
    (ESTADO_LLAMADA_ENTRANTE, "LLamada entrante"),
    (ESTADO_LLAMADA_LLAMANDO, "LLamando"),
    (ESTADO_LLAMADA_PERDIDA, "Llamada perdida"),
    (ESTADO_LLAMADA_CONTESTADA, "Llamada contestada"),
    (ESTADO_LLAMADA_ATENDIDO, "Llamada atendida"),
)

# Quien llama
QUIEN_LLAMA_CLIENTE = "01"
QUIEN_LLAMA_OTROS = "02"

QUIEN_LLAMA_CHOICES = (
    (QUIEN_LLAMA_CLIENTE, "Llama cliente"),
    (QUIEN_LLAMA_OTROS, "Llama otros"),
)

# Estdo AMI
AMI_CHANNEL_ST_DOWN = "Down"
AMI_CHANNEL_ST_RSVR = "Rsrvd"
AMI_CHANNEL_ST_OFFHOOK = "OffHook"
AMI_CHANNEL_ST_DIALING = "Dialing"
AMI_CHANNEL_ST_RING = "Ring"
AMI_CHANNEL_ST_RINGING = "Ringing"
AMI_CHANNEL_ST_UP = "Up"
AMI_CHANNEL_ST_BUSY = "Busy"
AMI_CHANNEL_ST_DIALING_OFFHOOK = "Dialing Offhook"
AMI_CHANNEL_ST_PRE = "Pre-ring"
AMI_CHANNEL_ST_UNKNOWN = "Unknown"

AMI_CHANNEL_ST_TO_ESTADOS_DB = {
    AMI_CHANNEL_ST_RING: ESTADO_LLAMADA_ENTRANTE,
    AMI_CHANNEL_ST_RINGING: ESTADO_LLAMADA_ENTRANTE,
    AMI_CHANNEL_ST_UP: ESTADO_LLAMADA_ATENDIDO,
}

# Estado de finalización de servicio
FINALIZA_SERVICIO_PENDIENTE = "01"
FINALIZA_SERVICIO_REALIZADO = "02"
FINALIZA_SERVICIO_CANCELCLIENTE = "03"
FINALIZA_SERVICIO_CANCELCONDUCTOR = "04"
FINALIZA_SERVICIO_CHOICES = (
    (FINALIZA_SERVICIO_PENDIENTE, "Pendiente"),
    (FINALIZA_SERVICIO_REALIZADO, "Realizado"),
    (FINALIZA_SERVICIO_CANCELCLIENTE, "Cancelado Cliente"),
    (FINALIZA_SERVICIO_CANCELCONDUCTOR, "Cancelado Conductor"),
)
