# Estados de vehiculo
CAR_ESTADO_PENDIENTE = "01"
CAR_ESTADO_FUERASERVICIO = "02"
CAR_ESTADO_ACTIVO = "03"
CAR_ESTADO_BAJA = "04"

CAR_ESTADO_CHOICES = (
    (CAR_ESTADO_PENDIENTE, "Pendiente"),
    (CAR_ESTADO_FUERASERVICIO, "Fuera servicio"),
    (CAR_ESTADO_ACTIVO, "Activo"),
    (CAR_ESTADO_BAJA, "Baja"),
)

# Estados de alquiler (vehículo para alquiler)
CAR_ESTADO_ALQUILER_NOAPLICA = "01"
CAR_ESTADO_ALQUILER_ALQUILADO = "02"
CAR_ESTADO_ALQUILER_LIBERADO = "03"

CAR_ESTADO_ALQUILER_CHOICES = (
    (CAR_ESTADO_ALQUILER_NOAPLICA, "No Aplica"),
    (CAR_ESTADO_ALQUILER_ALQUILADO, "Alquilado"),
    (CAR_ESTADO_ALQUILER_LIBERADO, "Liberado"),
)

# Estado del alquiler
ESTADO_ALQUILER_PENDIENTE = "01"  # usa
ESTADO_ALQUILER_PROGRAMADO = "02"
ESTADO_ALQUILER_ACTIVO = "03"  # usa
ESTADO_ALQUILER_CONCLUIDO = "04"  # usa
ESTADO_ALQUILER_CANCELADO = "05"
ESTADO_ALQUILER_REPROGRAMADO = "06"

ESTADO_ALQUILER_CHOICES = (
    (ESTADO_ALQUILER_PENDIENTE, "Pendiente"),
    (ESTADO_ALQUILER_PROGRAMADO, "Programado"),
    (ESTADO_ALQUILER_ACTIVO, "En proceso"),
    (ESTADO_ALQUILER_CONCLUIDO, "Concluido"),
    (ESTADO_ALQUILER_CANCELADO, "Cancelado"),
    (ESTADO_ALQUILER_REPROGRAMADO, "Reprogramado"),
)
