# Generated by Django 5.0.8 on 2024-10-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_conductor", "0001_initial"),
        ("core_maestras", "0001_initial"),
        ("core_operador", "0001_initial"),
        ("core_vehiculo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TurnoConductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "fecha_programacion",
                    models.DateField(verbose_name="Fecha programación"),
                ),
                (
                    "hora_programacion",
                    models.TimeField(verbose_name="Hora programación"),
                ),
                (
                    "fecha_fin_programacion",
                    models.DateField(verbose_name="Fecha fin programación"),
                ),
                (
                    "hora_fin_programacion",
                    models.TimeField(verbose_name="Hora fin programación"),
                ),
                (
                    "hora_inicio",
                    models.TimeField(blank=True, null=True, verbose_name="Hora inicio"),
                ),
                (
                    "hora_fin",
                    models.TimeField(blank=True, null=True, verbose_name="Hora fin"),
                ),
                (
                    "horas_efectivas",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora efectiva"
                    ),
                ),
                (
                    "monto_generado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Monto generado",
                    ),
                ),
                (
                    "servicios_asignados",
                    models.IntegerField(default=0, verbose_name="Servicios asignados"),
                ),
                (
                    "servicios_atendidos",
                    models.IntegerField(default=0, verbose_name="Servicios atendidos"),
                ),
                (
                    "servicios_cancelados",
                    models.IntegerField(default=0, verbose_name="Servicios cancelados"),
                ),
                (
                    "estado_turno",
                    models.CharField(
                        choices=[
                            ("01", "Pendiente"),
                            ("02", "Programado"),
                            ("03", "En proceso"),
                            ("04", "Concluido"),
                            ("05", "Cancelado"),
                            ("06", "Reprogramado"),
                        ],
                        default="01",
                        max_length=2,
                        verbose_name="Estado Turno",
                    ),
                ),
                (
                    "observacion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Obs. servicio",
                    ),
                ),
                (
                    "conductor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_conductor.conductor",
                    ),
                ),
                (
                    "horario_inicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_maestras.horario",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_vehiculo.vehiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno conductor",
                "verbose_name_plural": "Turnos conductores",
                "index_together": {
                    ("estado_turno", "fecha_programacion", "hora_programacion")
                },
            },
        ),
        migrations.CreateModel(
            name="TurnoOperador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "extension_numero",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Extensión"
                    ),
                ),
                (
                    "fecha_programacion",
                    models.DateField(verbose_name="Fecha programación"),
                ),
                (
                    "hora_programacion",
                    models.TimeField(verbose_name="Hora programación"),
                ),
                (
                    "hora_fin_programacion",
                    models.TimeField(verbose_name="Hora fin programación"),
                ),
                (
                    "hora_inicio",
                    models.TimeField(blank=True, null=True, verbose_name="Hora inicio"),
                ),
                (
                    "hora_fin",
                    models.TimeField(blank=True, null=True, verbose_name="Hora fin"),
                ),
                (
                    "horas_efectivas",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora efectiva"
                    ),
                ),
                (
                    "llamadas_atendidos",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="llamdas atendidos"
                    ),
                ),
                (
                    "servicios_registradas",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Servicios registradas"
                    ),
                ),
                (
                    "servicios_asignadas",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Servicios asignadas"
                    ),
                ),
                (
                    "estado_turno",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "Pendiente"),
                            ("02", "Programado"),
                            ("03", "En proceso"),
                            ("04", "Concluido"),
                            ("05", "Cancelado"),
                            ("06", "Reprogramado"),
                        ],
                        default="01",
                        max_length=2,
                        verbose_name="Estado Turno",
                    ),
                ),
                (
                    "observacion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Obs. servicio",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_maestras.horario",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_operador.operador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno operador",
                "verbose_name_plural": "Turnos operadores",
                "index_together": {
                    ("estado_turno", "fecha_programacion", "hora_programacion")
                },
            },
        ),
    ]
