# Generated by Django 5.0.8 on 2024-10-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_turno", "0001_initial"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="turnoconductor",
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="turnooperador",
            index_together=set(),
        ),
        migrations.AddField(
            model_name="turnoconductor",
            name="fecha_hora_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora fin"
            ),
        ),
        migrations.AddField(
            model_name="turnoconductor",
            name="fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora inicio"
            ),
        ),
        migrations.AddField(
            model_name="turnoconductor",
            name="programado_fecha_hora_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Programado fecha hora fin"
            ),
        ),
        migrations.AddField(
            model_name="turnoconductor",
            name="programado_fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Programado fecha hora inicio"
            ),
        ),
        migrations.AddField(
            model_name="turnoconductor",
            name="servicios_cancel_conductor",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Cancelado por conductor"
            ),
        ),
        migrations.AddField(
            model_name="turnooperador",
            name="fecha_hora_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora fin"
            ),
        ),
        migrations.AddField(
            model_name="turnooperador",
            name="fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora inicio"
            ),
        ),
        migrations.AddField(
            model_name="turnooperador",
            name="llamadas_otras",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="llamdas Otras"
            ),
        ),
        migrations.AddField(
            model_name="turnooperador",
            name="programado_fecha_hora_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Programado fecha hora fin"
            ),
        ),
        migrations.AddField(
            model_name="turnooperador",
            name="programado_fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Programado fecha hora inicio"
            ),
        ),
        migrations.AlterField(
            model_name="turnoconductor",
            name="servicios_asignados",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Servicios asignados"
            ),
        ),
        migrations.AlterField(
            model_name="turnoconductor",
            name="servicios_atendidos",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Servicios atendidos"
            ),
        ),
        migrations.AlterField(
            model_name="turnoconductor",
            name="servicios_cancelados",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Servicios cancelados"
            ),
        ),
        migrations.AlterIndexTogether(
            name="turnoconductor",
            index_together={
                (
                    "estado_turno",
                    "programado_fecha_hora_inicio",
                    "programado_fecha_hora_fin",
                    "fecha_hora_inicio",
                    "fecha_hora_fin",
                )
            },
        ),
        migrations.AlterIndexTogether(
            name="turnooperador",
            index_together={
                (
                    "estado_turno",
                    "programado_fecha_hora_inicio",
                    "programado_fecha_hora_fin",
                    "fecha_hora_inicio",
                    "fecha_hora_fin",
                )
            },
        ),
    ]
