# Generated by Django 5.0.8 on 2025-01-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_turno", "0002_alter_turnoconductor_index_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiciosDiaView",
            fields=[
                ("fecha", models.DateField(primary_key=True, serialize=False)),
                ("llamadas_atendidas", models.IntegerField(blank=True, null=True)),
                ("registrados", models.IntegerField(blank=True, null=True)),
                ("asignados", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "core_turno_serviciosrview",
                "managed": False,
            },
        ),
    ]
