# Generated by Django 5.0.8 on 2024-10-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "codigo",
                    models.SlugField(
                        blank=True,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Teléfono"
                    ),
                ),
                ("nombre", models.CharField(max_length=60, verbose_name="Nombre")),
                (
                    "apellido_paterno",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Apellido Paterno",
                    ),
                ),
                (
                    "apellido_materno",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Apellido Materno",
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=80, null=True, verbose_name="Correo"
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "Masculino"),
                            ("02", "Femenino"),
                            ("03", "No especifica"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Genero",
                    ),
                ),
                ("estado", models.BooleanField(default=False, verbose_name="Estado")),
                (
                    "servicios_realizados",
                    models.IntegerField(default=0, verbose_name="Servicios realizados"),
                ),
                (
                    "servicios_pendiente",
                    models.IntegerField(default=0, verbose_name="Servicios pendientes"),
                ),
                (
                    "servicios_cancelados",
                    models.IntegerField(default=0, verbose_name="Servicios cancelados"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
    ]
