# Generated by Django 5.0.8 on 2025-03-23 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_cliente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CliRutaFrecuente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "rutas",
                    models.JSONField(blank=True, null=True, verbose_name="Rutas"),
                ),
                (
                    "cliente",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruta_frecuente",
                        to="core_cliente.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruta frecuente",
                "verbose_name_plural": "Rutas frecuentes",
            },
        ),
    ]
