# Generated by Django 5.0.8 on 2024-10-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core_cliente", "0001_initial"),
        ("core_operador", "0001_initial"),
        ("core_turno", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Llamada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                ("anio", models.IntegerField(verbose_name="Año")),
                ("fecha_llamada", models.DateField(verbose_name="Fecha llamada")),
                ("hora_llamada", models.TimeField(verbose_name="Hora llamada")),
                ("numero", models.CharField(max_length=20, verbose_name="Numero")),
                (
                    "estado_llamada",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "LLamada entrante"),
                            ("02", "LLamando"),
                            ("03", "Llamada perdida"),
                            ("04", "Llamada atendida"),
                        ],
                        help_text="Estado de llamada",
                        max_length=2,
                        null=True,
                        verbose_name="Estado llamada",
                    ),
                ),
                (
                    "cerrar_llamada",
                    models.BooleanField(default=False, verbose_name="Cerrar llamada"),
                ),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Channel"
                    ),
                ),
                (
                    "channel_state_desc",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Channel State Desc",
                    ),
                ),
                (
                    "callerid_num",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Caller ID Num",
                    ),
                ),
                (
                    "callerid_name",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="Caller ID Name",
                    ),
                ),
                (
                    "uniqueid",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Uniqueid"
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Context"
                    ),
                ),
                (
                    "connected_channel",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Connected Channel",
                    ),
                ),
                (
                    "connected_channel_state_desc",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Connected Channel State Desc",
                    ),
                ),
                (
                    "connected_callerid_num",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Connected Num",
                    ),
                ),
                (
                    "bridgeid",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Bridge Id"
                    ),
                ),
                (
                    "linkedid",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Linkedid"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Duración"
                    ),
                ),
                (
                    "marca_tiempo_ami",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Marca de tiempo"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_cliente.cliente",
                    ),
                ),
                (
                    "operador_contesta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_operador.operador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Llamada",
                "verbose_name_plural": "Llamadas",
                "ordering": ["-id"],
                "index_together": {
                    ("anio", "numero", "estado_llamada", "linkedid", "marca_tiempo_ami")
                },
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "referencia_origen",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Ref. origen",
                    ),
                ),
                (
                    "referencia_destino",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Ref. destino",
                    ),
                ),
                (
                    "ubicacion_origen",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Ubi. origen"
                    ),
                ),
                (
                    "ubicacion_destino",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Ubi. destino",
                    ),
                ),
                (
                    "fecha_programacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha programación"
                    ),
                ),
                (
                    "hora_programacion",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora programación"
                    ),
                ),
                (
                    "pasajeros",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Pasajeros"
                    ),
                ),
                (
                    "monto_servicio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Monto servicio",
                    ),
                ),
                (
                    "observacion_registro",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Obs. registro",
                    ),
                ),
                (
                    "observacion_asignacion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Obs. asignación",
                    ),
                ),
                (
                    "observacion_servicio",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Obs. servicio",
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(blank=True, null=True, verbose_name="Hora inicio"),
                ),
                (
                    "hora_fin",
                    models.TimeField(blank=True, null=True, verbose_name="Hora fin"),
                ),
                (
                    "horas_efectivas",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora efectiva"
                    ),
                ),
                (
                    "estado",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Estado"
                    ),
                ),
                (
                    "estado_finaliza_servicio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("01", "Pendiente"),
                            ("02", "Realizado"),
                            ("03", "Cancelado"),
                        ],
                        default="01",
                        max_length=2,
                        null=True,
                        verbose_name="Estado finaliza servicio",
                    ),
                ),
                (
                    "eliminado",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Eliminado"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_cliente.cliente",
                    ),
                ),
                (
                    "llamada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_servicio.llamada",
                    ),
                ),
                (
                    "operador_asigna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operador_asigna",
                        to="core_operador.operador",
                    ),
                ),
                (
                    "operador_registra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operador_registra",
                        to="core_operador.operador",
                    ),
                ),
                (
                    "turno_conductor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_turno.turnoconductor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "index_together": {
                    (
                        "estado",
                        "eliminado",
                        "estado_finaliza_servicio",
                        "hora_inicio",
                        "hora_fin",
                        "operador_registra",
                    )
                },
            },
        ),
    ]
