# Generated by Django 5.0.8 on 2024-10-27 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_maestras", "0001_initial"),
        ("core_operador", "0002_alter_cathorariooperardordetalle_fecha_fin_and_more"),
        ("core_servicio", "0001_initial"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="llamada",
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="servicio",
            index_together=set(),
        ),
        migrations.AddField(
            model_name="llamada",
            name="fecha_hora_llamada",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora llamada"
            ),
        ),
        migrations.AddField(
            model_name="llamada",
            name="horario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_maestras.horario",
            ),
        ),
        migrations.AddField(
            model_name="llamada",
            name="otra_llamada",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Otra llamada"
            ),
        ),
        migrations.AddField(
            model_name="llamada",
            name="tipo_quien_llama",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "LLamada entrante"),
                    ("02", "LLamando"),
                    ("03", "Llamada perdida"),
                    ("04", "Llamada contestada"),
                    ("05", "Llamada atendida"),
                ],
                default="01",
                max_length=2,
                null=True,
                verbose_name="Quien llama",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="fecha_hora_fin",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora fin"
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha hora inicio"
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="horario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_maestras.horario",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="programado_fecha_hora_inicio",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Programado fecha hora inicio"
            ),
        ),
        migrations.AlterField(
            model_name="llamada",
            name="estado_llamada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "LLamada entrante"),
                    ("02", "LLamando"),
                    ("03", "Llamada perdida"),
                    ("04", "Llamada contestada"),
                    ("05", "Llamada atendida"),
                ],
                help_text="Estado de llamada",
                max_length=2,
                null=True,
                verbose_name="Estado llamada",
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="estado_finaliza_servicio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("01", "Pendiente"),
                    ("02", "Realizado"),
                    ("03", "Cancelado Cliente"),
                    ("04", "Cancelado Conductor"),
                ],
                default="01",
                max_length=2,
                null=True,
                verbose_name="Estado finaliza servicio",
            ),
        ),
        migrations.AlterIndexTogether(
            name="llamada",
            index_together={
                (
                    "anio",
                    "numero",
                    "estado_llamada",
                    "fecha_hora_llamada",
                    "linkedid",
                    "marca_tiempo_ami",
                    "tipo_quien_llama",
                )
            },
        ),
        migrations.AlterIndexTogether(
            name="servicio",
            index_together={
                (
                    "estado",
                    "horario",
                    "eliminado",
                    "estado_finaliza_servicio",
                    "programado_fecha_hora_inicio",
                    "fecha_hora_inicio",
                    "fecha_hora_fin",
                    "operador_registra",
                )
            },
        ),
    ]
