# Generated by Django 5.0.8 on 2025-01-25 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_operador", "0002_alter_cathorariooperardordetalle_fecha_fin_and_more"),
        ("core_servicio", "0002_alter_llamada_index_together_and_more"),
        ("core_turno", "0003_serviciosdiaview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicioModificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "referencia_origen",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Ref. origen",
                    ),
                ),
                (
                    "referencia_destino",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Ref. destino",
                    ),
                ),
                (
                    "ubicacion_origen",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Ubi. origen"
                    ),
                ),
                (
                    "ubicacion_destino",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Ubi. destino",
                    ),
                ),
                (
                    "programado_fecha_hora_inicio",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Programado fecha hora inicio",
                    ),
                ),
                (
                    "pasajeros",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Pasajeros"
                    ),
                ),
                (
                    "observacion_asignacion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Obs. asignación",
                    ),
                ),
                (
                    "observacion_servicio",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Obs. servicio",
                    ),
                ),
                (
                    "fecha_hora_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha hora inicio"
                    ),
                ),
                (
                    "fecha_hora_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha hora fin"
                    ),
                ),
                (
                    "operador_asigna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operador_asigna_modificado",
                        to="core_operador.operador",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicio_modificado",
                        to="core_servicio.servicio",
                    ),
                ),
                (
                    "turno_conductor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_turno.turnoconductor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio Modificado",
                "verbose_name_plural": "Servicios Modificados",
                "index_together": {
                    (
                        "programado_fecha_hora_inicio",
                        "fecha_hora_inicio",
                        "fecha_hora_fin",
                    )
                },
            },
        ),
    ]
