# estados de conductor
CONDUCTOR_ESTADO_PENDIENTE = "01"
CONDUCTOR_ESTADO_AUSENTE = "02"
CONDUCTOR_ESTADO_OCUPADO = "03"
CONDUCTOR_ESTADO_DISPONIBLE = "04"
CONDUCTOR_ESTADO_BAJA = "05"

CONDUCTOR_ESTADO_CHOICES = (
    (CONDUCTOR_ESTADO_PENDIENTE, "Pendiente"),
    (CONDUCTOR_ESTADO_AUSENTE, "Ausente"),
    (CONDUCTOR_ESTADO_OCUPADO, "Ocupado"),
    (CONDUCTOR_ESTADO_DISPONIBLE, "Disponible"),
    (CONDUCTOR_ESTADO_BAJA, "Baja"),
)
