GENERO_MASCULINO = "01"
GENERO_FEMENINO = "02"
GENERO_NOESPECIFICA = "03"

GENERO_CHOICES = (
    (GENERO_MASCULINO, "Masculino"),
    (GENERO_FEMENINO, "Femenino"),
    (GENERO_NOESPECIFICA, "No especifica"),
)
