# Generated by Django 5.0.8 on 2024-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnvironmentVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "name",
                    models.SlugField(
                        max_length=60, unique=True, verbose_name="nombre de la variable"
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=255, verbose_name="valor de la variable"
                    ),
                ),
                (
                    "es_activo",
                    models.BooleanField(default=False, verbose_name="Activo"),
                ),
            ],
            options={
                "verbose_name": "variable de entorno",
                "verbose_name_plural": "variables de entorno",
            },
        ),
    ]
