# Generated by Django 5.0.8 on 2024-10-09 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrupoHorario",
            fields=[
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(blank=True, max_length=20, verbose_name="Nombre"),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("estado", models.BooleanField(default=False, verbose_name="Estado")),
                (
                    "confirmado",
                    models.BooleanField(default=False, verbose_name="Confirmado"),
                ),
            ],
            options={
                "verbose_name": "Grupo de Horario",
                "verbose_name_plural": "Grupo de Horarios",
                "index_together": {("estado", "confirmado")},
            },
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "cod_horario",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Código",
                    ),
                ),
                ("nom_horario", models.CharField(max_length=20, verbose_name="Nombre")),
                (
                    "inicio_horario",
                    models.TimeField(blank=True, null=True, verbose_name="Incio"),
                ),
                (
                    "fin_horario",
                    models.TimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "orden_view",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Orden vista"
                    ),
                ),
                ("estado", models.BooleanField(default=False, verbose_name="Estado")),
                (
                    "horario_base",
                    models.BooleanField(default=False, verbose_name="Horario Base"),
                ),
            ],
            options={
                "verbose_name": "Horario",
                "verbose_name_plural": "Horario",
                "index_together": {("estado", "horario_base")},
            },
        ),
        migrations.CreateModel(
            name="GrupoHorarioDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="creado por"
                    ),
                ),
                (
                    "modified_by",
                    models.CharField(
                        editable=False, max_length=20, verbose_name="modificado por"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de modificación"
                    ),
                ),
                (
                    "dia_semana",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ],
                        verbose_name="Dia de la semana",
                    ),
                ),
                (
                    "orden_view",
                    models.SmallIntegerField(blank=True, null=True, verbose_name=""),
                ),
                ("estado", models.BooleanField(default=False, verbose_name="Estado")),
                (
                    "confirmado",
                    models.BooleanField(default=False, verbose_name="Confirmado"),
                ),
                (
                    "grupo_horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_maestras.grupohorario",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_maestras.horario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo Horario detalle",
                "verbose_name_plural": "Grupo Horarios detalle",
                "ordering": ["grupo_horario", "dia_semana", "orden_view"],
                "unique_together": {("grupo_horario", "dia_semana", "horario")},
                "index_together": {("estado", "grupo_horario")},
            },
        ),
    ]
